on:
  push:
    branches:
      - master

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Package
      run: |
        make setup clean
        make
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "Package" || echo "No changes to commit"
        git push origin HEAD:master
