name: sample-workflow
on:
  issues:
    types: [opened, assigned, labeled]

  pull_request:
    branches:
      - test-pr-workflow
    types:
      - labeled
      - opened

jobs:
  handle-prs:
    name: Handle PRs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Breakglass PR integration
      uses: ./
      with:
        slack_hook: ${{ secrets.SLACK_HOOK }}
        skip_ci_label: the-label-that-triggers-ci-skip
        skip_approval_label: the-label-that-triggers-approval-skiip
        github_token: ${{ secrets.GITHUB_TOKEN }}
        required_checks: "ci/circleci: test,ci/circleci: lint"
        instructions: |
            ## Checklists

            - [ ] Please do this
