name: sample-breakglass
on:
  issues:
    types: [labeled]

  pull_request:
    branches:
      - test-pr-workflow
    types:
      - labeled
      - opened

jobs:
  breakglass:
    name: Breaking the glass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Handle event
      uses: ./
      with:
        slack_hook: ${{ secrets.SLACK_HOOK }}
        skip_ci_label: the-label-that-triggers-ci-skip
        skip_approval_label: the-label-that-triggers-approval-skip
        github_token: ${{ secrets.GITHUB_TOKEN }}
        relevant_labels: "console-access"
        required_checks: "ci/circleci: test,ci/circleci: lint"
        circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}
        circle_ci_project_slug: 'github/my-org/my-project'
        circle_ci_workflow_name: 'build_and_test'
        instructions: |
            ## Checklists

            - [ ] Please do this
