name: sample-breakglass
on:
  schedule:
    - cron:  '0 0 * * *'

  issues:
    types: [labeled]

  pull_request:
    branches:
      - master
    types:
      - labeled
      - opened

jobs:
  breakglass:
    name: Breaking the glass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Handle event
      uses: ./
      with:
        slack_hook: ${{ secrets.SLACK_HOOK }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        relevant_labels: "console-access"
        required_checks: "ci/circleci: test,ci/circleci: lint"
