name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        make setup lint test dist/index.js
